services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: teamfinder_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: teamfinder_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    depends_on:
      - db
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             gunicorn team_finder.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
  media_data:
  static_data:
